version: "3"


networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: "172.30.0.0/24"


services:
  neo4j:
    image: neo4j
    networks:
      network:
        ipv4_address: 172.30.0.1
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data:rw
      - $HOME/neo4j/logs:/Logs:rw
    environment:
      - NEO4J_server_memory_pagecache_size=4G

  sms:
    image: ghcr.io/jadjer/rideonline_sms:latest
    networks:
      network:
        ipv4_address: 172.30.0.2

  auth:
    image: ghcr.io/jadjer/rideonline_auth:latest
    networks:
      network:
        ipv4_address: 172.30.0.3
    depends_on:
      - sms
      - neo4j
    ports:
      - "8000:8000"
    volumes:
      - $HOME/keys:/app/keys:ro
    environment:
      - DATABASE_HOST=172.30.0.1
      - DATABASE_PORT=7687
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - PUBLIC_KEY_PATH=/app/keys/public_key.pem
      - PRIVATE_KEY_PATH=/app/keys/private_key.pem
      - SMS_SERVICE=http://172.30.0.2:8000/api/v1
